package com.yuno.common.enums;

public enum EventType {
    PAYMENT_INITIATED, ROUTING_DECIDED, PROVIDER_CALLED, PROVIDER_SUCCESS,
    PROVIDER_FAILED, RETRY_TRIGGERED, FAILOVER_TRIGGERED,
    PAYMENT_SUCCESS, PAYMENT_FAILED, IDEMPOTENCY_HIT
}
